version: "3"

networks:
    weminds:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks:
            - weminds

    mysql:
        image: mysql:latest
        container_name: ${APP_NAME}_mysql
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        tty: true
        ports:
            - "4306:4306"
        volumes:
            - ./docker/dbdata:/var/lib/mysql
            - ./docker/config/php.ini:/usr/local/etc/php/conf.d/php.ini
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - weminds

    php:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: ${APP_NAME}_php
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - weminds

    phpmyadmin:
        depends_on:
            - mysql
            - php
        image: phpmyadmin/phpmyadmin
        container_name: ${APP_NAME}_pma
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            -   ./docker/config/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - weminds
    
    cache:
        container_name: ${APP_NAME}_cache
        image: redis:6.2.5-alpine
        ports:
            - '6379:6379'
        networks:
            - weminds