title: Backend
updated_by: 307a9721-c0ad-4af2-b00a-d49f1532e44b
updated_at: 1633055155
blueprint: categories
content: '<div class="text-backendColor inline-block w-auto px-3 py-1 text-sm font-semibold tracking-widest capitalize rounded-xl bg-red-100">Backend</div>'
