title: Design
updated_by: 307a9721-c0ad-4af2-b00a-d49f1532e44b
updated_at: 1633055259
blueprint: categories
content: '<div class="text-designColor inline-block w-auto px-3 py-1 text-sm font-semibold tracking-widest capitalize rounded-xl bg-blue-100">Design</div>'
